name: Deploy to Workshop

on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: vurv78/gmod-upload@59b6207bb40fbe8fc01d5464c8e57e06ebee9c14
        with:
          id: 2466875474
          changelog: "${{ github.event.head_commit.message }}"
        env:
          STEAM_USERNAME: ${{ secrets.STEAM_USERNAME }}
          STEAM_PASSWORD: ${{ secrets.STEAM_PASSWORD }}
