name: Deploy to Workshop

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: leafo/gh-actions-lua@v10
        with:
          luaVersion: "luajit-2.1.0-beta3"

      - name: Run gma packer
        run: |
          lua .github/workflows/gma.lua webaudio.gma

      - name: Upload to workshop
      - uses: arma-actions/workshop-upload@v1
        with:
          appId: '4000'
          itemId: '2466875474'
          contentPath: 'webaudio.gma'
          changelog: 'Automatic deployment'
        env:
          STEAM_USERNAME: ${{ secrets.STEAM_USERNAME }}
          STEAM_PASSWORD: ${{ secrets.STEAM_PASSWORD }}