name: Deploy to Workshop

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: vurv78/gmod-upload@1dc0e55186f8bcababee54992ae73fa68c8b9d23
        with:
          id: 2466875474
          changelog: "Deployment via Github to latest changes"
        env:
          STEAM_USERNAME: ${{ secrets.STEAM_USERNAME }}
          STEAM_PASSWORD: ${{ secrets.STEAM_PASSWORD }}
