name: Deploy to Workshop

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: wiremod/workshop-upload@9cfec5903ada8a0b27c16a7071b0e7c5276ca70a
        with:
          id: 2466875474
          changelog: "Deployment via Github to latest changes"
        env:
          STEAM_USERNAME: ${{ secrets.STEAM_USERNAME }}
          STEAM_PASSWORD: ${{ secrets.STEAM_PASSWORD }}
