name: Glua Linter

# Just runs GluaFixer https://github.com/FPtje/GLuaFixer on the repo.
# Derived from ACF-3's workflow

on:
  push:
    paths:
    - 'lua/**'
    - '!lua/entities/gmod_wire_expression2/**' # Ignore E2 path since it uses preprocessor stuff.
  pull_request:
    paths:
    - 'lua/**'
    - '!lua/entities/gmod_wire_expression2/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    
    - name: Download GluaFixer 1.17.3
      run: |
        curl -o glualint.zip -L https://github.com/FPtje/GLuaFixer/releases/latest/download/glualint-1.17.3-linux.zip
        unzip glualint.zip

    - name: Remove E2 Extension Folder
      run: rm -r lua/entities/gmod_wire_expression2/

    - name: Lint Code
      run: ./glualint lua